
import DAL.DBConnect;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class controllerNav extends javax.swing.JFrame {

    public void setUp(){
        controllMain.setVisible(true);
        jScContentMain.setVisible(true);
        cs.setVisible(false);
        cncs.setVisible(false);
        st.setVisible(false);
        cnst.setVisible(false);
        f.setVisible(false);
        cnf.setVisible(false);
        DefaultTableModel mode = (DefaultTableModel)jTableContentMain.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String query = "select count(*) from KhachHang;";
            ResultSet rs = db.ExcuteQueryGet(query);
            rs.next();
            tb_maKH.setText(Integer.toString(rs.getInt(1)+1)); 
        } catch (Exception e) {
            System.err.println("Cant get quantity customer\n");
        }
         
    }
    /**
     * Creates new form mainFrame
     */
    public controllerNav() {
        initComponents();
        setUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controll = new javax.swing.JPanel();
        main = new javax.swing.JButton();
        drinkAndFood = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        controllMain = new javax.swing.JPanel();
        f = new javax.swing.JPanel();
        st = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_maKH = new javax.swing.JLabel();
        lb_tenKH = new javax.swing.JLabel();
        lb_SDT = new javax.swing.JLabel();
        lb_CCCD = new javax.swing.JLabel();
        lb_tenTK = new javax.swing.JLabel();
        lb_matkhau = new javax.swing.JLabel();
        lb_nap = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        tb_maKH = new javax.swing.JTextField();
        tb_tenKH = new javax.swing.JTextField();
        tb_SDT = new javax.swing.JTextField();
        tb_CCCD = new javax.swing.JTextField();
        tb_tenTK = new javax.swing.JTextField();
        tb_matkhau = new javax.swing.JTextField();
        tb_nap = new javax.swing.JTextField();
        content = new javax.swing.JLayeredPane();
        contentMain = new javax.swing.JPanel();
        cnf = new javax.swing.JPanel();
        cnst = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cncs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScContentMain = new javax.swing.JScrollPane();
        jTableContentMain = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setLabel("Main");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        drinkAndFood.setText("Drink & Food");
        drinkAndFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkAndFoodActionPerformed(evt);
            }
        });

        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        staff.setText("Staff");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });

        controllMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout fLayout = new javax.swing.GroupLayout(f);
        f.setLayout(fLayout);
        fLayout.setHorizontalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        fLayout.setVerticalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        controllMain.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        jLabel9.setText("Mã Nhân Viên:");

        jLabel10.setText("Tên Nhân Viên:");

        jLabel11.setText("Địa Chỉ");

        jLabel12.setText("SĐT:");

        jLabel13.setText("CCCD");

        jButton3.setText("Thêm Nhân Viên");

        javax.swing.GroupLayout stLayout = new javax.swing.GroupLayout(st);
        st.setLayout(stLayout);
        stLayout.setHorizontalGroup(
            stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(stLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        stLayout.setVerticalGroup(
            stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(stLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        controllMain.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        jLabel1.setText("Mã Khách Hàng:");

        jLabel2.setText("Tên Khách Hàng:");

        jLabel3.setText("SĐT:");

        jLabel4.setText("CCCD:");

        jLabel5.setText("Mật Khẩu Cũ:");

        jLabel6.setText("jLabel1");

        jLabel7.setText("Mật Khẩu Mới:");

        jLabel8.setText("Tên Tài Khoản");

        jButton1.setText("Thay Đổi Thông Tin");

        jButton2.setText("Đổi Mật Khẩu");

        javax.swing.GroupLayout csLayout = new javax.swing.GroupLayout(cs);
        cs.setLayout(csLayout);
        csLayout.setHorizontalGroup(
            csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csLayout.createSequentialGroup()
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(csLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(csLayout.createSequentialGroup()
                                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField7)))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(csLayout.createSequentialGroup()
                                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField2))))))
                .addContainerGap())
        );
        csLayout.setVerticalGroup(
            csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(csLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(160, 160, 160)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controllMain.add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        lb_maKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_maKH.setText("Mã Khách Hàng:");
        controllMain.add(lb_maKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        lb_tenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_tenKH.setText("Tên:");
        controllMain.add(lb_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        lb_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_SDT.setText("SĐT:");
        controllMain.add(lb_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, -1, -1));

        lb_CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_CCCD.setText("CCCD");
        controllMain.add(lb_CCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, -1, -1));

        lb_tenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_tenTK.setText("Tài Khoản:");
        controllMain.add(lb_tenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 211, -1, -1));

        lb_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_matkhau.setText("Mật Khẩu");
        controllMain.add(lb_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        lb_nap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_nap.setText("Nạp:");
        controllMain.add(lb_nap, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, -1, -1));

        btn_add.setText("Thêm Tài Khoản");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        controllMain.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 331, 367, -1));

        tb_maKH.setEnabled(false);
        controllMain.add(tb_maKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 49, 246, -1));
        controllMain.add(tb_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 89, 246, -1));
        controllMain.add(tb_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 131, 246, -1));
        controllMain.add(tb_CCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 171, 246, -1));
        controllMain.add(tb_tenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 211, 246, -1));
        controllMain.add(tb_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 251, 246, -1));
        controllMain.add(tb_nap, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 291, 246, -1));

        javax.swing.GroupLayout controllLayout = new javax.swing.GroupLayout(controll);
        controll.setLayout(controllLayout);
        controllLayout.setHorizontalGroup(
            controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main)
                .addGap(18, 18, 18)
                .addComponent(drinkAndFood)
                .addGap(18, 18, 18)
                .addComponent(customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staff)
                .addContainerGap())
            .addComponent(controllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        controllLayout.setVerticalGroup(
            controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main)
                    .addComponent(drinkAndFood)
                    .addComponent(customer)
                    .addComponent(staff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout cnfLayout = new javax.swing.GroupLayout(cnf);
        cnf.setLayout(cnfLayout);
        cnfLayout.setHorizontalGroup(
            cnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        cnfLayout.setVerticalGroup(
            cnfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        contentMain.add(cnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Địa Chỉ", "SDT", "CCCD"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout cnstLayout = new javax.swing.GroupLayout(cnst);
        cnst.setLayout(cnstLayout);
        cnstLayout.setHorizontalGroup(
            cnstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnstLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        cnstLayout.setVerticalGroup(
            cnstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnstLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        contentMain.add(cnst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "SĐT", "CCCD"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout cncsLayout = new javax.swing.GroupLayout(cncs);
        cncs.setLayout(cncsLayout);
        cncsLayout.setHorizontalGroup(
            cncsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cncsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
        );
        cncsLayout.setVerticalGroup(
            cncsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        contentMain.add(cncs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTableContentMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Tên Tài Khoản", "Số Dư"
            }
        ));
        jScContentMain.setViewportView(jTableContentMain);

        contentMain.add(jScContentMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 606, 409));

        content.setLayer(contentMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content)
        );

        getAccessibleContext().setAccessibleName("frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        lb_CCCD.setVisible(true);
        lb_SDT.setVisible(true);
        lb_maKH.setVisible(true);
        lb_matkhau.setVisible(true);
        lb_nap.setVisible(true);
        lb_tenKH.setVisible(true);
        lb_tenKH.setVisible(true);
        btn_add.setVisible(true);
        cncs.setVisible(false);
        cs.setVisible(false);
        st.setVisible(false);
        cnst.setVisible(false);
        f.setVisible(false);
        cnf.setVisible(false);
        controllMain.setVisible(true);
        jScContentMain.setVisible(true);
        DefaultTableModel mode = (DefaultTableModel)jTableContentMain.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String query = "select kh.maKH,kh.tenKH,kh.SDT,tk.tenTK,tk.tienTK from TaiKhoan tk join KhachHang kh on tk.maKH=kh.maKH;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getInt(5)});
            }  
        } catch (Exception e) {
            System.out.println("Error\n");
        }
    }//GEN-LAST:event_mainActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        
        DefaultTableModel mode = (DefaultTableModel)jTableContentMain.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String queryKH = "insert into KhachHang(maKH,tenKH,SDT,CCCD) values ("+tb_maKH.getText()+",'"+tb_tenKH.getText()+"',"+tb_SDT.getText()+","+tb_CCCD.getText()+");";
            db.ExcuteQuerySet(queryKH);
            String queryTK = "insert into TaiKhoan(tenTK,maKH,matkhau,tienTK) values ('"+tb_tenTK.getText()+"',"+tb_maKH.getText()+",'"+tb_matkhau.getText()+"',"+tb_nap.getText()+");";
            db.ExcuteQuerySet(queryTK);
            
            mode.setRowCount(0);
            String query = "select kh.maKH,kh.tenKH,kh.SDT,tk.tenTK,tk.tienTK from TaiKhoan tk join KhachHang kh on tk.maKH=kh.maKH;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getInt(5)});
            }  
            tb_maKH.setText(String.valueOf(Integer.valueOf(tb_maKH.getText())+1));
        } catch (Exception e) {
            System.out.println("Error\n");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void drinkAndFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkAndFoodActionPerformed
        lb_CCCD.setVisible(false);
        lb_SDT.setVisible(false);
        lb_maKH.setVisible(false);
        lb_matkhau.setVisible(false);
        lb_nap.setVisible(false);
        lb_tenKH.setVisible(false);
        lb_tenKH.setVisible(false);
        btn_add.setVisible(false);
        cs.setVisible(false);
        cncs.setVisible(false);
        cnst.setVisible(true);
        st.setVisible(true);
        jScrollPane2.setVisible(true);
        jScContentMain.setVisible(false);
        f.setVisible(true);
        cnf.setVisible(true);
        
    }//GEN-LAST:event_drinkAndFoodActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        lb_CCCD.setVisible(false);
        lb_SDT.setVisible(false);
        lb_maKH.setVisible(false);
        lb_matkhau.setVisible(false);
        lb_nap.setVisible(false);
        lb_tenKH.setVisible(false);
        lb_tenKH.setVisible(false);
        btn_add.setVisible(false);
        cncs.setVisible(true);
        cs.setVisible(true);
        cnst.setVisible(false);
        st.setVisible(false);
        f.setVisible(false);
        cnf.setVisible(false);
        jScContentMain.setVisible(false);
        DBConnect db = new DBConnect();
        DefaultTableModel mode = (DefaultTableModel)jTable1.getModel();
        try {
            mode.setRowCount(0);
            String query = "select * from KhachHang;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4)});
            }  
        } catch (Exception e) {
            System.out.println("Error Cus\n");
        }
        
        
    }//GEN-LAST:event_customerActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        lb_CCCD.setVisible(false);
        lb_SDT.setVisible(false);
        lb_maKH.setVisible(false);
        lb_matkhau.setVisible(false);
        lb_nap.setVisible(false);
        lb_tenKH.setVisible(false);
        lb_tenKH.setVisible(false);
        btn_add.setVisible(false);
        cs.setVisible(false);
        cncs.setVisible(false);
        cnst.setVisible(true);
        st.setVisible(true);
        f.setVisible(false);
        cnf.setVisible(false);
        jScrollPane2.setVisible(true);
        jScContentMain.setVisible(false);
        DBConnect db = new DBConnect();
        DefaultTableModel mode = (DefaultTableModel)jTable2.getModel();
        try {
            mode.setRowCount(0);
            String query = "select * from NhanVien;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }  
        } catch (Exception e) {
            System.out.println("Error St\n");
        }
    }//GEN-LAST:event_staffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controllerNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controllerNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controllerNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controllerNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controllerNav().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JPanel cncs;
    private javax.swing.JPanel cnf;
    private javax.swing.JPanel cnst;
    private javax.swing.JLayeredPane content;
    private javax.swing.JPanel contentMain;
    private javax.swing.JPanel controll;
    private javax.swing.JPanel controllMain;
    private javax.swing.JPanel cs;
    private javax.swing.JButton customer;
    private javax.swing.JButton drinkAndFood;
    private javax.swing.JPanel f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScContentMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableContentMain;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lb_CCCD;
    private javax.swing.JLabel lb_SDT;
    private javax.swing.JLabel lb_maKH;
    private javax.swing.JLabel lb_matkhau;
    private javax.swing.JLabel lb_nap;
    private javax.swing.JLabel lb_tenKH;
    private javax.swing.JLabel lb_tenTK;
    private javax.swing.JButton main;
    private javax.swing.JPanel st;
    private javax.swing.JButton staff;
    private javax.swing.JTextField tb_CCCD;
    private javax.swing.JTextField tb_SDT;
    private javax.swing.JTextField tb_maKH;
    private javax.swing.JTextField tb_matkhau;
    private javax.swing.JTextField tb_nap;
    private javax.swing.JTextField tb_tenKH;
    private javax.swing.JTextField tb_tenTK;
    // End of variables declaration//GEN-END:variables
}
