
import DAL.DBConnect;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class mainFrame extends javax.swing.JFrame {

    public void setUp(){
        DefaultTableModel mode = (DefaultTableModel)jTable1.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String query = "select count(*) from KhachHang;";
            ResultSet rs = db.ExcuteQueryGet(query);
            rs.next();
            tb_maKH.setText(Integer.toString(rs.getInt(1)+1)); 
        } catch (Exception e) {
            System.err.println("Cant get quantity customer\n");
        }
         
    }
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        controll = new javax.swing.JPanel();
        main = new javax.swing.JButton();
        drinkAndFood = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        controllMain = new javax.swing.JPanel();
        lb_maKH = new javax.swing.JLabel();
        lb_tenKH = new javax.swing.JLabel();
        lb_SDT = new javax.swing.JLabel();
        lb_CCCD = new javax.swing.JLabel();
        lb_tenTK = new javax.swing.JLabel();
        lb_matkhau = new javax.swing.JLabel();
        lb_nap = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        tb_maKH = new javax.swing.JTextField();
        tb_tenKH = new javax.swing.JTextField();
        tb_SDT = new javax.swing.JTextField();
        tb_CCCD = new javax.swing.JTextField();
        tb_tenTK = new javax.swing.JTextField();
        tb_matkhau = new javax.swing.JTextField();
        tb_nap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên", "SDT", "Tài khoản", "Số dư"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        main.setLabel("Main");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        drinkAndFood.setText("Drink & Food");

        customer.setText("Customer");

        staff.setText("Staff");

        lb_maKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_maKH.setText("Mã Khách Hàng:");

        lb_tenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_tenKH.setText("Tên:");

        lb_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_SDT.setText("SĐT:");

        lb_CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_CCCD.setText("CCCD");

        lb_tenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_tenTK.setText("Tài Khoản:");

        lb_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_matkhau.setText("Mật Khẩu");

        lb_nap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_nap.setText("Nạp:");

        btn_add.setText("Thêm Tài Khoản");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        tb_maKH.setEnabled(false);

        javax.swing.GroupLayout controllMainLayout = new javax.swing.GroupLayout(controllMain);
        controllMain.setLayout(controllMainLayout);
        controllMainLayout.setHorizontalGroup(
            controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controllMainLayout.createSequentialGroup()
                        .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_maKH)
                            .addComponent(lb_tenKH)
                            .addComponent(lb_SDT)
                            .addComponent(lb_CCCD)
                            .addComponent(lb_tenTK)
                            .addComponent(lb_matkhau)
                            .addComponent(lb_nap))
                        .addGap(18, 18, 18)
                        .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_maKH)
                            .addComponent(tb_tenKH)
                            .addComponent(tb_SDT)
                            .addComponent(tb_CCCD)
                            .addComponent(tb_tenTK)
                            .addComponent(tb_matkhau)
                            .addComponent(tb_nap))))
                .addContainerGap())
        );
        controllMainLayout.setVerticalGroup(
            controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllMainLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_maKH)
                    .addComponent(tb_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenKH)
                    .addComponent(tb_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_SDT)
                    .addComponent(tb_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CCCD)
                    .addComponent(tb_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenTK)
                    .addComponent(tb_tenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_matkhau)
                    .addComponent(tb_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(controllMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nap)
                    .addComponent(tb_nap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout controllLayout = new javax.swing.GroupLayout(controll);
        controll.setLayout(controllLayout);
        controllLayout.setHorizontalGroup(
            controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main)
                .addGap(18, 18, 18)
                .addComponent(drinkAndFood)
                .addGap(18, 18, 18)
                .addComponent(customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(staff)
                .addContainerGap())
            .addComponent(controllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        controllLayout.setVerticalGroup(
            controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main)
                    .addComponent(drinkAndFood)
                    .addComponent(customer)
                    .addComponent(staff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controllMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(controll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        DefaultTableModel mode = (DefaultTableModel)jTable1.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String query = "select kh.maKH,kh.tenKH,kh.SDT,tk.tenTK,tk.tienTK from TaiKhoan tk join KhachHang kh on tk.maKH=kh.maKH;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getInt(5)});
            }  
        } catch (Exception e) {
            System.out.println("Error\n");
        }
    }//GEN-LAST:event_mainActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        DefaultTableModel mode = (DefaultTableModel)jTable1.getModel();
        mode.setRowCount(0);
        try {
            DBConnect db = new DBConnect();
            String queryKH = "insert into KhachHang(maKH,tenKH,SDT,CCCD) values ("+tb_maKH.getText()+",'"+tb_tenKH.getText()+"',"+tb_SDT.getText()+","+tb_CCCD.getText()+");";
            db.ExcuteQuerySet(queryKH);
            String queryTK = "insert into TaiKhoan(tenTK,maKH,matkhau,tienTK) values ('"+tb_tenTK.getText()+"',"+tb_maKH.getText()+",'"+tb_matkhau.getText()+"',"+tb_nap.getText()+");";
            db.ExcuteQuerySet(queryTK);
            
            mode.setRowCount(0);
            String query = "select kh.maKH,kh.tenKH,kh.SDT,tk.tenTK,tk.tienTK from TaiKhoan tk join KhachHang kh on tk.maKH=kh.maKH;";
            ResultSet rs = db.ExcuteQueryGet(query);
            while(rs.next()){
                mode.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getInt(5)});
            }  
            tb_maKH.setText(String.valueOf(Integer.valueOf(tb_maKH.getText())+1));
        } catch (Exception e) {
            System.out.println("Error\n");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JPanel content;
    private javax.swing.JPanel controll;
    private javax.swing.JPanel controllMain;
    private javax.swing.JButton customer;
    private javax.swing.JButton drinkAndFood;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_CCCD;
    private javax.swing.JLabel lb_SDT;
    private javax.swing.JLabel lb_maKH;
    private javax.swing.JLabel lb_matkhau;
    private javax.swing.JLabel lb_nap;
    private javax.swing.JLabel lb_tenKH;
    private javax.swing.JLabel lb_tenTK;
    private javax.swing.JButton main;
    private javax.swing.JButton staff;
    private javax.swing.JTextField tb_CCCD;
    private javax.swing.JTextField tb_SDT;
    private javax.swing.JTextField tb_maKH;
    private javax.swing.JTextField tb_matkhau;
    private javax.swing.JTextField tb_nap;
    private javax.swing.JTextField tb_tenKH;
    private javax.swing.JTextField tb_tenTK;
    // End of variables declaration//GEN-END:variables
}
